"""add_date_range_to_availability

Revision ID: 0623c46c157e
Revises: 004_date_required
Create Date: 2025-11-25 15:16:00.224829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0623c46c157e'
down_revision = '004_date_required'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availabilities', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('availabilities', sa.Column('end_date', sa.Date(), nullable=False))
    op.alter_column('availabilities', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('availabilities', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('availabilities', 'end_date')
    op.drop_column('availabilities', 'start_date')
    # ### end Alembic commands ###



